# This is a config for E2B sandbox template.
# You can use template ID (wp73mftugqzz0p72blwv) or template name (vibely-nextjs-app) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibely-nextjs-app") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibely-nextjs-app") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibely-nextjs-app')

team_id = "bebf6873-7afa-439f-bf10-b18910896553"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibely-nextjs-app"
template_id = "wp73mftugqzz0p72blwv"
